import PvNP.FormulaStructuralSchedule

/-!
# Variable-width raw-formula schedule bridge

`FormulaStructuralSchedule` routes supplied frozen views and positive-depth raw
formulas through arbitrary nonempty ratio-regime schedules, but asks callers to
supply a width bound for the truth-table/path-DNF child views. This module
instantiates that bound with the generic theorem already available for those
views:

  `widthDNF (formulaDNFView child).D <= n`.

## HONEST SCOPE STATEMENT (read this)

* This removes one caller-supplied width predicate by choosing the broad
  truth-table fallback width `w = n`.
* The ratio-regime schedule hypotheses are still supplied. Since `w = n` is
  usually very large, those hypotheses may be strong or vacuous in interesting
  asymptotic regimes.
* This is not efficient recursive B4 decomposition, does not synthesize
  product/counting hypotheses, and does not prove a global efficient
  `t(d,s)` theorem for arbitrary syntax.
* Formula-collapse infrastructure only: NOT a Frege/PHP proof-size lower
  bound, NOT a PHP switching lemma, NOT an NP/circuit lower bound, NOT a
  statement about P vs NP.

INTEGRITY: no `sorry`, no `admit`, no new `axiom`, no `native_decide`.
-/

namespace PvNP
namespace FormulaVarWidthSchedule

open CNFModel
open BoundedDepthFrege
open BoundedDepthRestriction
open BoundedDepthDecisionTree
open BoundedDepthLayerView
open BoundedDepthIteratedCollapse
open GeneratedOneStepDepthReduction
open GeneratedRefinedCollapse
open ScheduledAutoCollapse
open FrozenProductSchedule
open FrozenProductScheduleRatio
open FormulaTruthTableView
open FormulaStructuralSchedule
open FrozenDepthView
open SwitchingEncodeConstruct
open SwitchingLemmaStatement

/-! ## Formula-derived variable-width bounds -/

theorem topConnectiveFormula_child_width_le_vars {n : Nat}
    (children : List (BDFormula n)) :
    forall child, child ∈ children -> widthDNF (formulaDNFView child).D <= n := by
  intro child _hchild
  exact widthDNF_formulaDNFView_le child

theorem positiveDepthFormula_child_width_le_vars {n : Nat}
    (F : BDFormula n) :
    forall child, child ∈ topChildren F ->
      widthDNF (formulaDNFView child).D <= n := by
  intro child _hchild
  exact widthDNF_formulaDNFView_le child

/-! ## Ratio-regime collapse at width `n` -/

open GeneratedRefinedIteratedCertificate in
/-- **Top-connective raw formula ratio-regime collapse at variable width.**
The immediate child views are generated by the truth-table/path-DNF fallback,
so the width parameter is fixed to `n` and no separate child-width hypothesis is
needed.

The ratio-regime schedule is still supplied; this theorem removes only the
width-bound caller obligation. -/
theorem topConnectiveFormula_ratioRegimeCollapseWithVarWidth
    (sched : List ScheduleStage) {n : Nat} (p : ParentKind)
    (children : List (BDFormula n))
    (hm : 1 <= children.length)
    (hreg : RegimeFrom children.length n (stars (freeRestriction n)) sched)
    (hd : 0 < sched.length) :
    exists cert : GeneratedRefinedIteratedCertificate n (freeRestriction n)
        (p.merge children) sched.length,
      cert.stageGateCounts = List.replicate sched.length children.length /\
      cert.stageBudgets = sched.map stageS /\
      cert.stageStarCounts = sched.map stageStars /\
      TreeBudgetFrom
        (fun _depth s => children.length * (s - 1))
        children.length sched.length sched /\
      exists T : DTree n, exists s : Nat,
        cert.lastStage = some (T, children.length, s) /\
        (forall a : Assignment n, dtEval a T = eval a cert.finalFormula) /\
        dtDepth T <= children.length * (s - 1) /\
        (forall a : Assignment n, Agree cert.finalComposed a ->
          dtEval a T = eval a (restrict cert.finalComposed
            (p.merge children))) := by
  let V := topConnectiveFrozenDepthView p children
  have hlen : V.gateCount = children.length :=
    topConnectiveFrozenDepthView_gateCount p children
  have hmV : 1 <= V.gateCount := by
    rw [hlen]
    exact hm
  have hwV : forall g, g ∈ V.layer.gates -> widthDNF g.theDNF <= n := by
    simpa [V] using topConnectiveFrozenDepthView_width_le_vars p children
  have hregV : RegimeFrom V.gateCount n (stars (freeRestriction n)) sched := by
    rw [hlen]
    exact hreg
  obtain ⟨cert, hgc, hb, hsc, _ht, T, s, hlast, heval, hdepth, hsem⟩ :=
    frozenDepthView_ratioRegimeCollapseWithGlobalTreeBudget
      sched n V hmV hwV hregV hd
  refine ⟨cert, ?_, hb, hsc, ?_, T, s, ?_, heval, ?_, hsem⟩
  · rw [hgc, hlen]
  · exact constantGateTreeBudget children.length sched sched.length
  · rw [hlen] at hlast
    exact hlast
  · simpa [V, hlen, frozenGlobalTreeBudget] using hdepth

open GeneratedRefinedIteratedCertificate in
/-- **Positive-depth raw formula ratio-regime collapse at variable width.**
Every non-leaf raw formula is exposed at its top connective, its immediate
children are viewed through the truth-table/path-DNF fallback, and the supplied
ratio-regime schedule is instantiated at width `n`.

This is a global tree-budget route for raw positive-depth syntax under a
supplied ratio regime, not an efficient structural B4 theorem. -/
theorem positiveDepthFormula_ratioRegimeCollapseWithVarWidth
    (sched : List ScheduleStage) {n : Nat} (F : BDFormula n)
    (hpos : 0 < depth F)
    (hm : 1 <= topChildCount F)
    (hreg : RegimeFrom (topChildCount F) n (stars (freeRestriction n)) sched)
    (hd : 0 < sched.length) :
    exists cert : GeneratedRefinedIteratedCertificate n (freeRestriction n)
        F sched.length,
      cert.stageGateCounts = List.replicate sched.length (topChildCount F) /\
      cert.stageBudgets = sched.map stageS /\
      cert.stageStarCounts = sched.map stageStars /\
      TreeBudgetFrom
        (fun _depth s => topChildCount F * (s - 1))
        (topChildCount F) sched.length sched /\
      exists T : DTree n, exists s : Nat,
        cert.lastStage = some (T, topChildCount F, s) /\
        (forall a : Assignment n, dtEval a T = eval a cert.finalFormula) /\
        dtDepth T <= topChildCount F * (s - 1) /\
        (forall a : Assignment n, Agree cert.finalComposed a ->
          dtEval a T = eval a (restrict cert.finalComposed F)) := by
  exact
    positiveDepthFormula_ratioRegimeCollapseWithGlobalTreeBudget
      sched n F hpos hm (positiveDepthFormula_child_width_le_vars F) hreg hd

end FormulaVarWidthSchedule
end PvNP
