import PvNP.BoundedDepthIteratedCollapse

/-!
# Gate B, stages B1-B2: good restrictions GENERATED by counting

The first theorems in this repository where the switching lemma's COUNTING
produces restrictions instead of consuming them.  Every existing stage /
schedule theorem (`generatedDNFStage_exists`, `generatedKLayerCollapse_exists`,
...) takes its restriction as a SUPPLIED hypothesis; here we close that gap:

* `jointBadSet` — the union of the per-gate bad sets of a list of gates;
* `jointBadSet_card_le` — the UNION BOUND: at most
  `m * (|restrictionsWithStars n (ℓ-s)| * (8w)^s)` restrictions are bad for
  any of `m` gates (per-gate bound = the proved SimpleDNF switching lemma /
  its CNF dual);
* `goodRestriction_exists` — whenever the union bound beats the size of the
  `ℓ`-star restriction space, a SINGLE restriction exists that is
  simultaneously good for every gate;
* `simultaneousCollapse_exists` — under that same counting hypothesis, one
  restriction collapses EVERY gate formula to a decision tree of depth `< s`
  simultaneously (the input B3's depth-reduction step will consume).

## Gate B target statement (frozen at B1, per the goal document)

The goal theorem `generatedIteratedCollapse` (stage B4) shall state: for a
single `BDFormula` presented with a LAYERED simple-view structure of depth
`d`, bottom width `≤ w`, and `≤ m` bottom-layer gates, and every stage budget
`s`: iterating `simultaneousCollapse_exists` layer by layer — collapsing all
bottom gates under one counting-generated restriction, converting the shallow
trees back into formulas (`treeToFormula`), and merging into the layer above
— yields, under an explicit product-of-stages counting hypothesis
`B(m, w, s, d) < (space sizes)`, a composed restriction sequence and a
decision tree of depth `≤ t(d, s)` computing the fully restricted formula,
with explicit depth and size accounting at every stage.  The layered-view
structure and the merge step are stage-B3 deliverables.

## HONEST SCOPE STATEMENT (read this)

* These are counting-form corollaries of the PROVED SimpleDNF switching
  lemma (`SwitchingClose2.switchingLemmaTermSimple_proved`) and its CNF
  dual.  Everything is exact `Finset.card` counting; no probability measure.
* A formula-collapse result: NOT a Frege/PHP proof-size bound, NOT an
  NP/circuit bound, NOT a statement about P vs NP.  Gate A rung 4 (the
  matching switching lemma) remains open.
* The closed-form cardinality of `restrictionsWithStars` is NOT proved here
  (recorded B3 prerequisite for non-vacuous instantiation of the headline
  bound at scale); non-vacuity below is witnessed through the DIRECT
  cardinality hypothesis instead.

INTEGRITY: no `sorry`, no `admit`, no new `axiom`, no `native_decide`.
-/

namespace PvNP
namespace GeneratedGoodRestriction

open CNFModel
open BoundedDepthFrege
open BoundedDepthDecisionTree
open BoundedDepthRestriction
open BoundedDepthLayerView
open BoundedDepthIteratedCollapse
open SwitchingEncodeConstruct
open SwitchingLemmaStatement
open BoundedDepthCanonicalDT
open SwitchingTermCanonicalDT

/-- Restrictions inherit decidable equality from their underlying function
type (the same `inferInstanceAs` pattern as `instFintypeRestriction`). -/
instance instDecidableEqRestriction (n : Nat) : DecidableEq (Restriction n) :=
  inferInstanceAs (DecidableEq (Fin n → Option Bool))

/-! ## Gate specifications -/

/-- A bottom-layer gate: a bounded-depth formula carrying a simple DNF view
or a simple CNF view (the latter switches through its dual DNF). -/
inductive GateSpec (n : Nat) where
  | dnf (F : BDFormula n) (V : DNFView F)
  | cnf (F : BDFormula n) (V : CNFView F)

namespace GateSpec

/-- The gate's formula. -/
def formula {n : Nat} : GateSpec n → BDFormula n
  | .dnf F _ => F
  | .cnf F _ => F

/-- The DNF to which the switching lemma applies (the view's DNF, or the
dual DNF of the view's CNF). -/
def theDNF {n : Nat} : GateSpec n → DNF n
  | .dnf _ V => V.D
  | .cnf _ V => cnfDualDNF V.C

/-- The switching DNF of every gate is simple. -/
theorem theDNF_simple {n : Nat} (g : GateSpec n) : SimpleDNF g.theDNF := by
  cases g with
  | dnf F V => exact V.simple
  | cnf F V => exact simpleDNF_cnfDualDNF_of_simpleCNF V.simple

end GateSpec

/-! ## The joint bad set and the union bound -/

/-- The set of restrictions bad for at least one gate. -/
noncomputable def jointBadSet {n : Nat} (gates : List (GateSpec n))
    (s ℓ : Nat) : Finset (Restriction n) :=
  gates.foldr (fun g acc => badSetTerm g.theDNF s ℓ ∪ acc) ∅

theorem mem_jointBadSet {n : Nat} {gates : List (GateSpec n)} {s ℓ : Nat}
    {ρ : Restriction n} :
    ρ ∈ jointBadSet gates s ℓ ↔
      ∃ g ∈ gates, ρ ∈ badSetTerm g.theDNF s ℓ := by
  induction gates with
  | nil =>
      simp [jointBadSet]
  | cons g gates ih =>
      simp only [jointBadSet, List.foldr_cons, Finset.mem_union] at *
      constructor
      · rintro (h | h)
        · exact ⟨g, List.mem_cons_self g gates, h⟩
        · rcases ih.mp h with ⟨g', hg', hρ⟩
          exact ⟨g', List.mem_cons_of_mem g hg', hρ⟩
      · rintro ⟨g', hg', hρ⟩
        rcases List.mem_cons.mp hg' with he | hg'
        · subst he
          exact Or.inl hρ
        · exact Or.inr (ih.mpr ⟨g', hg', hρ⟩)

/-- **The union bound (B2).**  At most
`m * (|restrictionsWithStars n (ℓ-s)| * (8w)^s)` restrictions are bad for any
of `m` width-`≤ w` gates — per-gate bound supplied by the PROVED switching
lemma. -/
theorem jointBadSet_card_le {n : Nat} (gates : List (GateSpec n))
    (w s ℓ : Nat) (hwidth : ∀ g ∈ gates, widthDNF g.theDNF ≤ w) :
    (jointBadSet gates s ℓ).card ≤
      gates.length *
        ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) := by
  induction gates with
  | nil =>
      simp [jointBadSet]
  | cons g gates ih =>
      have hg := SwitchingClose2.switchingLemmaTermSimple_proved (n := n)
        g.theDNF w s ℓ g.theDNF_simple (hwidth g (List.mem_cons_self g gates))
      have hrest := ih (fun g' hg' => hwidth g' (List.mem_cons_of_mem g hg'))
      calc (jointBadSet (g :: gates) s ℓ).card
          ≤ (badSetTerm g.theDNF s ℓ).card + (jointBadSet gates s ℓ).card :=
            Finset.card_union_le _ _
        _ ≤ (restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s +
              gates.length *
                ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) :=
            Nat.add_le_add hg hrest
        _ = (gates.length + 1) *
              ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) :=
            Eq.trans (Nat.add_comm _ _) (Nat.succ_mul gates.length _).symm
        _ = (g :: gates).length *
              ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) := by
            rw [List.length_cons]

/-- Factor-4 joint bad-set union bound (S2176), via exact `RCode` card. -/
theorem jointBadSet_card_le4 {n : Nat} (gates : List (GateSpec n))
    (w s ℓ : Nat) (hwidth : ∀ g ∈ gates, widthDNF g.theDNF ≤ w) :
    (jointBadSet gates s ℓ).card ≤
      gates.length *
        ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) := by
  induction gates with
  | nil =>
      simp [jointBadSet]
  | cons g gates ih =>
      have hg := SwitchingClose2.switchingLemmaTermSimple_proved4 (n := n)
        g.theDNF w s ℓ g.theDNF_simple (hwidth g (List.mem_cons_self g gates))
      have hrest := ih (fun g' hg' => hwidth g' (List.mem_cons_of_mem g hg'))
      calc (jointBadSet (g :: gates) s ℓ).card
          ≤ (badSetTerm g.theDNF s ℓ).card + (jointBadSet gates s ℓ).card :=
            Finset.card_union_le _ _
        _ ≤ (restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s +
              gates.length *
                ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) :=
            Nat.add_le_add hg hrest
        _ = (gates.length + 1) *
              ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) :=
            Eq.trans (Nat.add_comm _ _) (Nat.succ_mul gates.length _).symm
        _ = (g :: gates).length *
              ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) := by
            rw [List.length_cons]

/-! ## Good restrictions exist by counting -/

/-- **Counting produces a restriction (direct form).**  If strictly fewer
restrictions are jointly bad than there are `ℓ`-star restrictions, a single
`ℓ`-star restriction exists that is good for EVERY gate simultaneously. -/
theorem goodRestriction_exists_of_card {n : Nat} (gates : List (GateSpec n))
    (s ℓ : Nat)
    (hcard : (jointBadSet gates s ℓ).card <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ gates, ρ ∉ badSetTerm g.theDNF s ℓ := by
  have hsdiff : 0 <
      ((restrictionsWithStars n ℓ) \ jointBadSet gates s ℓ).card := by
    have hle := Finset.le_card_sdiff (jointBadSet gates s ℓ)
      (restrictionsWithStars n ℓ)
    omega
  obtain ⟨ρ, hρ⟩ := Finset.card_pos.mp hsdiff
  rw [Finset.mem_sdiff] at hρ
  refine ⟨ρ, hρ.1, ?_⟩
  intro g hg hbad
  exact hρ.2 (mem_jointBadSet.mpr ⟨g, hg, hbad⟩)

/-- **Counting produces a restriction (headline union-bound form).**  If the
union bound `m * (|restrictionsWithStars n (ℓ-s)| * (8w)^s)` beats the space
size, a simultaneously good `ℓ`-star restriction exists. -/
theorem goodRestriction_exists {n : Nat} (gates : List (GateSpec n))
    (w s ℓ : Nat) (hwidth : ∀ g ∈ gates, widthDNF g.theDNF ≤ w)
    (hbeat : gates.length *
        ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ gates, ρ ∉ badSetTerm g.theDNF s ℓ := by
  apply goodRestriction_exists_of_card
  calc (jointBadSet gates s ℓ).card
      ≤ gates.length *
          ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) :=
        jointBadSet_card_le gates w s ℓ hwidth
    _ < (restrictionsWithStars n ℓ).card := hbeat

/-- Factor-4 good-restriction existence (S2176). -/
theorem goodRestriction_exists4 {n : Nat} (gates : List (GateSpec n))
    (w s ℓ : Nat) (hwidth : ∀ g ∈ gates, widthDNF g.theDNF ≤ w)
    (hbeat : gates.length *
        ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ gates, ρ ∉ badSetTerm g.theDNF s ℓ := by
  apply goodRestriction_exists_of_card
  calc (jointBadSet gates s ℓ).card
      ≤ gates.length *
          ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) :=
        jointBadSet_card_le4 gates w s ℓ hwidth
    _ < (restrictionsWithStars n ℓ).card := hbeat

/-! ## Simultaneous collapse under one generated restriction -/

/-- Per-gate collapse for a good restriction, routed through the audited
bridges. -/
theorem gate_collapse {n : Nat} (g : GateSpec n) (w s ℓ : Nat)
    (hw : widthDNF g.theDNF ≤ w) (ρ : Restriction n)
    (hstars : ρ ∈ restrictionsWithStars n ℓ)
    (hgood : ρ ∉ badSetTerm g.theDNF s ℓ) :
    ∃ T : DTree n, dtDepth T < s ∧
      ∀ a : Assignment n, Agree ρ a →
        dtEval a T = eval a (restrict ρ g.formula) := by
  cases g with
  | dnf F V =>
      exact (bdFormula_dnfView_switching_collapse V w s ℓ hw).2 ρ hstars hgood
  | cnf F V =>
      exact (bdFormula_cnfView_dual_switching_collapse V w s ℓ hw).2
        ρ hstars hgood

/-- **B1/B2 keystone: simultaneous collapse by counting.**  Whenever the
union bound beats the `ℓ`-star space, there is ONE restriction under which
EVERY gate's formula collapses to a decision tree of depth `< s` — no
restriction is supplied; the counting generates it.  This is the input the
stage-B3 depth-reduction step consumes. -/
theorem simultaneousCollapse_exists {n : Nat} (gates : List (GateSpec n))
    (w s ℓ : Nat) (hwidth : ∀ g ∈ gates, widthDNF g.theDNF ≤ w)
    (hbeat : gates.length *
        ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ gates, ∃ T : DTree n, dtDepth T < s ∧
        ∀ a : Assignment n, Agree ρ a →
          dtEval a T = eval a (restrict ρ g.formula) := by
  obtain ⟨ρ, hstars, hgood⟩ := goodRestriction_exists gates w s ℓ hwidth hbeat
  exact ⟨ρ, hstars, fun g hg =>
    gate_collapse g w s ℓ (hwidth g hg) ρ hstars (hgood g hg)⟩

/-- Factor-4 simultaneous collapse (S2176). -/
theorem simultaneousCollapse_exists4 {n : Nat} (gates : List (GateSpec n))
    (w s ℓ : Nat) (hwidth : ∀ g ∈ gates, widthDNF g.theDNF ≤ w)
    (hbeat : gates.length *
        ((restrictionsWithStars n (ℓ - s)).card * (4 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ gates, ∃ T : DTree n, dtDepth T < s ∧
        ∀ a : Assignment n, Agree ρ a →
          dtEval a T = eval a (restrict ρ g.formula) := by
  obtain ⟨ρ, hstars, hgood⟩ := goodRestriction_exists4 gates w s ℓ hwidth hbeat
  exact ⟨ρ, hstars, fun g hg =>
    gate_collapse g w s ℓ (hwidth g hg) ρ hstars (hgood g hg)⟩

/-! ## Interop: generated stages with a SHARED counting-generated restriction -/

/-- Every restriction has a total extension, so a single shared restriction
trivially satisfies the schedule machinery's common-extension hypotheses. -/
theorem restriction_has_extension {n : Nat} (ρ : Restriction n) :
    ∃ a : Assignment n, Agree ρ a := by
  refine ⟨fun v => (ρ v).getD false, ?_⟩
  intro v b hv
  simp [hv]

/-- Counting-generated simultaneous DNF stages: for a list of DNF-view gates,
one counting-generated restriction yields a `GeneratedDNFLayerStage` for every
gate, ALL sharing that restriction. -/
theorem generatedSimultaneousDNFStages_exist {n : Nat}
    (Fs : List ((F : BDFormula n) × DNFView F)) (w s ℓ : Nat)
    (hwidth : ∀ p ∈ Fs, widthDNF p.2.D ≤ w)
    (hbeat : Fs.length *
        ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ p ∈ Fs, ∃ S : GeneratedDNFLayerStage p.1,
        S.view = p.2 ∧ S.s = s ∧ S.ℓ = ℓ ∧ S.ρ = ρ := by
  have hgates : ∀ g ∈ Fs.map (fun p => GateSpec.dnf p.1 p.2),
      widthDNF (GateSpec.theDNF g) ≤ w := by
    intro g hg
    rcases List.mem_map.mp hg with ⟨p, hp, he⟩
    subst he
    exact hwidth p hp
  have hbeat' : (Fs.map (fun p => GateSpec.dnf p.1 p.2)).length *
      ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card := by
    rw [List.length_map]
    exact hbeat
  have hex : ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ Fs.map (fun p => GateSpec.dnf p.1 p.2),
        ρ ∉ badSetTerm (GateSpec.theDNF g) s ℓ :=
    goodRestriction_exists (n := n)
      (Fs.map (fun p => GateSpec.dnf p.1 p.2)) w s ℓ hgates hbeat'
  obtain ⟨ρ, hstars, hgood⟩ := hex
  refine ⟨ρ, hstars, ?_⟩
  intro p hp
  have hgoodp : ρ ∉ badSetTerm p.2.D s ℓ :=
    hgood (GateSpec.dnf p.1 p.2) (List.mem_map_of_mem _ hp)
  obtain ⟨S, hview, _, hs, hℓ, hρ, _⟩ := generatedDNFStage_exists
    p.2 w s ℓ (hwidth p hp) ρ hstars hgoodp
  exact ⟨S, hview, hs, hℓ, hρ⟩

/-- Counting-generated simultaneous CNF stages: for a list of CNF-view gates,
one counting-generated restriction yields a `GeneratedCNFLayerStage` for every
gate, all sharing that restriction.  This is the CNF dual companion to
`generatedSimultaneousDNFStages_exist`. -/
theorem generatedSimultaneousCNFStages_exist {n : Nat}
    (Fs : List ((F : BDFormula n) × CNFView F)) (w s ℓ : Nat)
    (hwidth : ∀ p ∈ Fs, widthDNF (cnfDualDNF p.2.C) ≤ w)
    (hbeat : Fs.length *
        ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ p ∈ Fs, ∃ S : GeneratedCNFLayerStage p.1,
        S.view = p.2 ∧ S.s = s ∧ S.ℓ = ℓ ∧ S.ρ = ρ := by
  have hgates : ∀ g ∈ Fs.map (fun p => GateSpec.cnf p.1 p.2),
      widthDNF (GateSpec.theDNF g) ≤ w := by
    intro g hg
    rcases List.mem_map.mp hg with ⟨p, hp, he⟩
    subst he
    exact hwidth p hp
  have hbeat' : (Fs.map (fun p => GateSpec.cnf p.1 p.2)).length *
      ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card := by
    rw [List.length_map]
    exact hbeat
  have hex : ∃ ρ ∈ restrictionsWithStars n ℓ,
      ∀ g ∈ Fs.map (fun p => GateSpec.cnf p.1 p.2),
        ρ ∉ badSetTerm (GateSpec.theDNF g) s ℓ :=
    goodRestriction_exists (n := n)
      (Fs.map (fun p => GateSpec.cnf p.1 p.2)) w s ℓ hgates hbeat'
  obtain ⟨ρ, hstars, hgood⟩ := hex
  refine ⟨ρ, hstars, ?_⟩
  intro p hp
  have hgoodp : ρ ∉ badSetTerm (cnfDualDNF p.2.C) s ℓ :=
    hgood (GateSpec.cnf p.1 p.2) (List.mem_map_of_mem _ hp)
  obtain ⟨S, hview, _, hs, hℓ, hρ, _⟩ := generatedCNFStage_exists
    p.2 w s ℓ (hwidth p hp) ρ hstars hgoodp
  exact ⟨S, hview, hs, hℓ, hρ⟩

/-- Counting-generated mixed DNF/CNF stages under one shared restriction.  The
explicit union bound ranges over the concatenated bottom-gate list, so the
restriction is generated once and then reused by every generated stage. -/
theorem generatedSimultaneousMixedStages_exist {n : Nat}
    (Ds : List ((F : BDFormula n) × DNFView F))
    (Cs : List ((F : BDFormula n) × CNFView F)) (w s ℓ : Nat)
    (hwidthD : ∀ p ∈ Ds, widthDNF p.2.D ≤ w)
    (hwidthC : ∀ p ∈ Cs, widthDNF (cnfDualDNF p.2.C) ≤ w)
    (hbeat : (Ds.length + Cs.length) *
        ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card) :
    ∃ ρ ∈ restrictionsWithStars n ℓ,
      (∀ p ∈ Ds, ∃ S : GeneratedDNFLayerStage p.1,
        S.view = p.2 ∧ S.s = s ∧ S.ℓ = ℓ ∧ S.ρ = ρ) ∧
      (∀ p ∈ Cs, ∃ S : GeneratedCNFLayerStage p.1,
        S.view = p.2 ∧ S.s = s ∧ S.ℓ = ℓ ∧ S.ρ = ρ) := by
  let gates : List (GateSpec n) :=
    Ds.map (fun p => GateSpec.dnf p.1 p.2) ++
      Cs.map (fun p => GateSpec.cnf p.1 p.2)
  have hgates : ∀ g ∈ gates, widthDNF (GateSpec.theDNF g) ≤ w := by
    intro g hg
    dsimp [gates] at hg
    rw [List.mem_append] at hg
    rcases hg with hg | hg
    · rcases List.mem_map.mp hg with ⟨p, hp, he⟩
      subst he
      exact hwidthD p hp
    · rcases List.mem_map.mp hg with ⟨p, hp, he⟩
      subst he
      exact hwidthC p hp
  have hbeat' : gates.length *
      ((restrictionsWithStars n (ℓ - s)).card * (8 * w) ^ s) <
      (restrictionsWithStars n ℓ).card := by
    dsimp [gates]
    rw [List.length_append, List.length_map, List.length_map]
    exact hbeat
  obtain ⟨ρ, hstars, hgood⟩ := goodRestriction_exists gates w s ℓ hgates hbeat'
  refine ⟨ρ, hstars, ?_, ?_⟩
  · intro p hp
    have hmem : GateSpec.dnf p.1 p.2 ∈ gates := by
      dsimp [gates]
      rw [List.mem_append]
      exact Or.inl (List.mem_map_of_mem _ hp)
    have hgoodp : ρ ∉ badSetTerm p.2.D s ℓ := hgood (GateSpec.dnf p.1 p.2) hmem
    obtain ⟨S, hview, _, hs, hℓ, hρ, _⟩ := generatedDNFStage_exists
      p.2 w s ℓ (hwidthD p hp) ρ hstars hgoodp
    exact ⟨S, hview, hs, hℓ, hρ⟩
  · intro p hp
    have hmem : GateSpec.cnf p.1 p.2 ∈ gates := by
      dsimp [gates]
      rw [List.mem_append]
      exact Or.inr (List.mem_map_of_mem _ hp)
    have hgoodp : ρ ∉ badSetTerm (cnfDualDNF p.2.C) s ℓ :=
      hgood (GateSpec.cnf p.1 p.2) hmem
    obtain ⟨S, hview, _, hs, hℓ, hρ, _⟩ := generatedCNFStage_exists
      p.2 w s ℓ (hwidthC p hp) ρ hstars hgoodp
    exact ⟨S, hview, hs, hℓ, hρ⟩

/-! ## Non-vacuity -/

/-- The empty-DNF view of the empty `or` formula. -/
def emptyGateView (n : Nat) : DNFView (BDFormula.or ([] : List (BDFormula n))) where
  D := []
  sem_eq := by
    intro a
    rw [eval_or]
    rfl
  simple := by
    intro t ht
    exact absurd ht (List.not_mem_nil t)

/-- The empty DNF has an empty bad set for any positive budget: its canonical
tree is a constant leaf. -/
theorem badSetTerm_nil {n : Nat} (s ℓ : Nat) (hs : 0 < s) :
    badSetTerm ([] : DNF n) s ℓ = ∅ := by
  rw [badSetTerm]
  apply Finset.filter_false_of_mem
  intro ρ _
  intro hdepth
  have : dtDepth (termCanonicalDT (dnfRestrict ρ ([] : DNF n))) = 0 := by
    have h1 : dnfRestrict ρ ([] : DNF n) = [] := rfl
    rw [h1]
    simp only [termCanonicalDT]
    rfl
  omega

/-- The `ℓ`-star space is nonempty for `ℓ ≤ n` (first `ℓ` variables starred,
the rest fixed `false`). -/
theorem restrictionsWithStars_nonempty {n ℓ : Nat} (hℓ : ℓ ≤ n) :
    (restrictionsWithStars n ℓ).Nonempty := by
  refine ⟨fun v => if v.val < ℓ then none else some false, ?_⟩
  rw [restrictionsWithStars, Finset.mem_filter]
  refine ⟨Finset.mem_univ _, ?_⟩
  rw [stars]
  have hset : (Finset.univ.filter
      (fun v : Fin n => (if v.val < ℓ then none else some false) = none)) =
      Finset.univ.filter (fun v : Fin n => v.val < ℓ) := by
    apply Finset.filter_congr
    intro v _
    by_cases hv : v.val < ℓ
    · simp [hv]
    · simp [hv]
  rw [hset]
  -- count the initial segment via the evident equivalence with `Fin ℓ`
  have hcard : (Finset.univ.filter (fun v : Fin n => v.val < ℓ)).card = ℓ := by
    have hsub : (Finset.univ.filter (fun v : Fin n => v.val < ℓ)).card =
        Fintype.card {v : Fin n // v.val < ℓ} :=
      (Fintype.card_subtype (fun v : Fin n => v.val < ℓ)).symm
    have hequiv : {v : Fin n // v.val < ℓ} ≃ Fin ℓ :=
      { toFun := fun v => ⟨v.1.val, v.2⟩
        invFun := fun m => ⟨⟨m.val, Nat.lt_of_lt_of_le m.isLt hℓ⟩, m.isLt⟩
        left_inv := fun v => rfl
        right_inv := fun m => rfl }
    rw [hsub, Fintype.card_congr hequiv, Fintype.card_fin]
  exact hcard

/-- **Non-vacuity of the counting route (direct form).**  A concrete instance
where the direct cardinality hypothesis holds and the conclusion is realized:
the singleton empty gate over any `n ≥ 1`, `ℓ = 1`, `s = 1`. -/
theorem goodRestriction_nonvacuous (n : Nat) (hn : 1 ≤ n) :
    ∃ ρ ∈ restrictionsWithStars n 1,
      ∀ g ∈ [GateSpec.dnf (BDFormula.or []) (emptyGateView n)],
        ρ ∉ badSetTerm g.theDNF 1 1 := by
  apply goodRestriction_exists_of_card
  have hempty : jointBadSet
      [GateSpec.dnf (BDFormula.or []) (emptyGateView n)] 1 1 = ∅ := by
    show badSetTerm ([] : DNF n) 1 1 ∪ ∅ = ∅
    rw [badSetTerm_nil 1 1 (by omega)]
    exact Finset.empty_union ∅
  rw [hempty]
  simp only [Finset.card_empty]
  exact Finset.card_pos.mpr (restrictionsWithStars_nonempty hn)

/-- **Non-vacuity of the mixed generated-stage route.**  In the singleton empty
DNF plus singleton empty CNF instance, the direct cardinality hypothesis produces
one shared restriction and both generated stage records with exact `s = 1`,
`ℓ = 1` accounting. -/
theorem generatedMixedEmptyStages_nonvacuous (n : Nat) (hn : 1 ≤ n) :
    ∃ ρ ∈ restrictionsWithStars n 1,
      (∃ S : GeneratedDNFLayerStage (BDFormula.or ([] : List (BDFormula n))),
        S.view = emptyGateView n ∧ S.s = 1 ∧ S.ℓ = 1 ∧ S.ρ = ρ) ∧
      (∃ S : GeneratedCNFLayerStage (BDFormula.tru : BDFormula n),
        S.view = emptyCNFView n ∧ S.s = 1 ∧ S.ℓ = 1 ∧ S.ρ = ρ) := by
  let Ds : List ((F : BDFormula n) × DNFView F) :=
    [⟨BDFormula.or [], emptyGateView n⟩]
  let Cs : List ((F : BDFormula n) × CNFView F) :=
    [⟨BDFormula.tru, emptyCNFView n⟩]
  have hwidthD : ∀ p ∈ Ds, widthDNF p.2.D ≤ 0 := by
    intro p hp
    dsimp [Ds] at hp
    simp only [List.mem_singleton] at hp
    subst p
    simp [emptyGateView]
  have hwidthC : ∀ p ∈ Cs, widthDNF (cnfDualDNF p.2.C) ≤ 0 := by
    intro p hp
    dsimp [Cs] at hp
    simp only [List.mem_singleton] at hp
    subst p
    simp [emptyCNFView, cnfDualDNF]
  have hbeat : (Ds.length + Cs.length) *
        ((restrictionsWithStars n (1 - 1)).card * (8 * 0) ^ 1) <
      (restrictionsWithStars n 1).card := by
    have hpos : 0 < (restrictionsWithStars n 1).card :=
      Finset.card_pos.mpr (restrictionsWithStars_nonempty hn)
    dsimp [Ds, Cs]
    simpa using hpos
  obtain ⟨ρ, hρ, hD, hC⟩ := generatedSimultaneousMixedStages_exist
    Ds Cs 0 1 1 hwidthD hwidthC hbeat
  refine ⟨ρ, hρ, ?_, ?_⟩
  · have hmem : (⟨BDFormula.or [], emptyGateView n⟩ :
        (F : BDFormula n) × DNFView F) ∈ Ds := by simp [Ds]
    simpa [Ds] using hD ⟨BDFormula.or [], emptyGateView n⟩ hmem
  · have hmem : (⟨BDFormula.tru, emptyCNFView n⟩ :
        (F : BDFormula n) × CNFView F) ∈ Cs := by simp [Cs]
    simpa [Cs] using hC ⟨BDFormula.tru, emptyCNFView n⟩ hmem

end GeneratedGoodRestriction
end PvNP
